services: 
  db:
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rental_db
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d rental_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
        
  webapp:
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__ConnectionString=Host=db;Port=5432;Username=admin;Password=admin;Database=rental_db
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://dashboard:18889
    depends_on:
      db:
        condition: service_healthy

volumes: 
  dbdata: